/**
 * Downloads fonts from Google Fonts into `public/fonts/` and generates
 * `src/styles/fonts.css` pointing at the local files.
 *
 * Why: the mockup linked the Google Fonts CDN. Production needs self-hosted
 * fonts, both for speed and so the page does not call a third party on every
 * visit.
 *
 * The subset is driven by the `text=` parameter: Google Fonts returns a file
 * containing exactly the listed glyphs. The stock `cyrillic` + `latin` ranges
 * cost 333 KB across three families — the whole page budget and then some.
 * A bespoke set fits in roughly a fifth of that.
 *
 * Run: `node scripts/fetch-fonts.mjs`. Not part of the build — the output is
 * committed so `npm run build` never touches the network.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const FONT_DIR = resolve(ROOT, 'public/fonts');
const CSS_OUT = resolve(ROOT, 'src/styles/fonts.css');

const RUSSIAN = 'абвгдеёжзийклмнопрстуфхцчшщъыьэюя';
const BELARUSIAN_EXTRA = 'іўґ'; // occur in names and quotations
const LATIN = 'abcdefghijklmnopqrstuvwxyz';
const DIGITS = '0123456789';

/**
 * Punctuation and symbols. `№` and `×` are named in the brief explicitly;
 * dashes, quotation marks and the arrow come from the mockup. The
 * non-breaking space and soft hyphen are needed or number layout falls apart.
 */
const PUNCTUATION = [
  ' !"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~',
  '\u00A0', // non-breaking space — the thousands separator
  '\u00AD', // soft hyphen
  '\u2009\u202F', // thin and narrow no-break spaces
  '«»„“”‘’', // quotation marks
  '—–‑', // dashes and the non-breaking hyphen
  '…·•', // ellipsis and dots
  '№§°%‰', // symbols
  '×÷±≈≤≥', // maths
  '→←↑↓', // arrows from the mockup
  '✓✔', // ticks
  '₽€$', // currency: BYN is spelled out, but the glyphs are cheap
].join('');

const SUBSET_TEXT = [
  RUSSIAN,
  RUSSIAN.toUpperCase(),
  BELARUSIAN_EXTRA,
  BELARUSIAN_EXTRA.toUpperCase(),
  LATIN,
  LATIN.toUpperCase(),
  DIGITS,
  PUNCTUATION,
].join('');

const FAMILIES = [
  { name: 'Onest', weights: [700, 800] },
  { name: 'Golos Text', weights: [400, 500, 600] },
  { name: 'Martian Mono', weights: [400, 500] },
];

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

function cssUrl(family, weight) {
  const name = family.replace(/ /g, '+');
  return (
    `https://fonts.googleapis.com/css2?family=${name}:wght@${weight}` +
    `&text=${encodeURIComponent(SUBSET_TEXT)}&display=swap`
  );
}

function fileNameFor(family, weight) {
  return `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}.woff2`;
}

async function main() {
  await mkdir(FONT_DIR, { recursive: true });

  const rules = [];
  let totalBytes = 0;

  for (const { name, weights } of FAMILIES) {
    for (const weight of weights) {
      const cssResponse = await fetch(cssUrl(name, weight), { headers: { 'User-Agent': UA } });
      if (!cssResponse.ok) throw new Error(`${name} ${weight}: CSS → ${cssResponse.status}`);
      const css = await cssResponse.text();

      // With `text=` Google serves the file from /l/font?kit=… rather than a
      // tidy path, so match on format('woff2') instead of the suffix.
      const url = /url\((https:\/\/[^)]+)\)\s*format\('woff2'\)/.exec(css)?.[1];
      if (!url) throw new Error(`${name} ${weight}: no woff2 in the response\n${css}`);

      const range = /unicode-range:\s*([^;]+);/.exec(css)?.[1]?.trim();

      // How many @font-face rules came back: with `text=` there must be exactly
      // one. Several would mean the subset was ignored and ranges arrived.
      const faceCount = (css.match(/@font-face/g) ?? []).length;
      if (faceCount !== 1) {
        throw new Error(`${name} ${weight}: expected one @font-face, got ${faceCount}`);
      }

      const fileResponse = await fetch(url, { headers: { 'User-Agent': UA } });
      if (!fileResponse.ok) throw new Error(`${name} ${weight}: file → ${fileResponse.status}`);
      const bytes = new Uint8Array(await fileResponse.arrayBuffer());

      const fileName = fileNameFor(name, weight);
      await writeFile(resolve(FONT_DIR, fileName), bytes);
      totalBytes += bytes.byteLength;
      console.log(`  ${fileName.padEnd(28)} ${(bytes.byteLength / 1024).toFixed(1)} KB`);

      rules.push(
        [
          `/* ${name} ${weight} */`,
          '@font-face {',
          `  font-family: '${name}';`,
          '  font-style: normal;',
          `  font-weight: ${weight};`,
          '  font-display: swap;',
          `  src: url('/fonts/${fileName}') format('woff2');`,
          ...(range === undefined ? [] : [`  unicode-range: ${range};`]),
          '}',
        ].join('\n'),
      );
    }
  }

  const header = [
    '/*',
    ' * Generated by `node scripts/fetch-fonts.mjs`. Do not edit by hand.',
    ' *',
    ' * Subset: Cyrillic (Russian + і/ў), Latin, digits, punctuation,',
    ` * № — · × and the rest from the mockup. ${(totalBytes / 1024).toFixed(1)} KB across seven weights.`,
    ' * Fonts under the SIL Open Font License; files in public/fonts/.',
    ' *',
    ' * A glyph outside the subset falls back to a system font — visible, not broken.',
    ' * If one is needed, add it to SUBSET_TEXT and regenerate.',
    ' */',
    '',
  ].join('\n');

  await writeFile(CSS_OUT, `${header}\n${rules.join('\n\n')}\n`, 'utf8');
  console.log(`\nTotal ${(totalBytes / 1024).toFixed(1)} KB → src/styles/fonts.css`);
}

await main();
